# Candidates Example: Column Analysis
This notebook loads `Candidates_example.csv` and displays all column names.

In [15]:
import pandas as pd

csv_path = 'Candidates_example.csv'
df = pd.read_csv(csv_path)
print(f'Loaded {csv_path} with {len(df):,} rows and {len(df.columns)} columns.')

/var/folders/km/gzfmffxn3219fbtl84mfnhq00000gn/T/ipykernel_12568/2036810965.py:4: DtypeWarning: Columns (1,2,4,16,18,20,21,22,23,24,25,26,27,28,29,30,44,45,46,47,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_path)

Loaded Candidates_example.csv with 6,218,281 rows and 50 columns.

In [16]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 0)

print(f'Total columns: {len(df.columns)}')
df.head(5)
# print('Column names:')

Total columns: 50

,WinnowCandidateKey,CreatedDate,UpdatedDate,NPI,ProfilePictureLink,FirstName,MiddleName,LastName,NickName,FullName,PhysicianType,Degree,Category,State,City,Address,PhoneNumber1,FaxNumber,ZipCode,Experience,Educations,Certifications,AwardsHonors,Publications,LicensureData,BoardCertifications,EducationTrainingLocation,EducationTrainingDate,EducationTrainingYears,ExperienceBinned,Email,IsActiveFlag,InactiveAt,Gender,PrimaryHospitalIDs,PhysicianGroupID,HospitalHistoryAffiliation,ChurnScore,Latitude,Longitude,TaxonomyCode,PhysicianRole,Speciality,SubSpeciality,ResidencyTrainingLocation,ResidencyTrainingDate,ResidencyTrainingYears,PublicationConnectionNPI,CandidateValidEmail,MedicalCode
0,2812426.0,2024-09-03 20:45:08.5518590,2024-09-03 20:45:08.5518590,1053802660,NaN,Abdullah,Mahmud,Mahmud,NaN,ABDULLAH MAHMUD MAHMUD,NaN,DDS,NaN,Michigan,FRASER,NaN,5862938750.0,NaN,480261867,0.0,[],[],[],[],[],[],[],[],[],0,NaN,True,NaN,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],[],[],[],NaN,NaN
1,NaN,NaN,NaN,1770851412,NaN,Rachel,Leigh,Lewis,NaN,RACHEL LEIGH LEWIS,NaN,NaN,NaN,New Mexico,TAOS,NaN,5757588575.0,5.052747e+09,875716489,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,1164003000,NaN,Camille,Elise,Barnes,NaN,CAMILLE ELISE BARNES,NaN,MD,NaN,Michigan,GRAND RAPIDS,NaN,6163913777.0,NaN,495032526,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,F,1.922091e+09,NaN,"[[""1457304495"",202109], [""1922090554"",202112]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[""CPT0241U"", ""CPT1123F"", ""CPT1124F"", ""CPT36415..."
3,2393258.0,2024-09-03 20:45:08.5518590,2024-09-03 20:45:08.5518590,1972094720,NaN,Ashley,E,Cline,NaN,ASHLEY E CLINE,NaN,BCABA,NaN,Michigan,BAY CITY,NaN,9899923497.0,NaN,487062367,0.0,[],[],[],[],[],[],[],[],[],0,NaN,True,NaN,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],[],[],[],NaN,NaN
4,NaN,NaN,NaN,1942792585,NaN,Katarzyna,NaN,Wegrzyn,NaN,KATARZYNA WEGRZYN,NaN,MD,NaN,Massachusetts,BOSTON,"850 HARRISON AVENUE, DOWLING 2N DEPARTMENT OF ...",6176388934.0,NaN,02118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,F,1.346218e+09,NaN,"[[""1346218294"",202111], [""1528195724"",202207],...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
npis_to_find = [
1063490852,
1194841254,
1790076586,
1336109925,
1457990731,
1518092048,
]

# Smaller dataframe with entries whose NPI is in npis_to_find.
npis_to_find_set = {str(npi).strip() for npi in npis_to_find}
matched_npi_df = df[df['NPI'].astype(str).str.strip().isin(npis_to_find_set)].copy()
print(f'Matched rows by NPI: {len(matched_npi_df):,}')

requested_columns = [
    'NPI',
    'degree',
    'educations',
    'experience',
    'certifications',
    'EducationTrainingLocation',
    'EducationTrainingDate',
    'EducationTrainingYears',
    'ResidencyTrainingLocation',
    'ResidencyTrainingDate',
    'ResidencyTrainingYears',
]

# Match requested names to actual dataframe columns, case-insensitively.
columns_lower_map = {c.lower(): c for c in matched_npi_df.columns}
selected_actual_columns = [columns_lower_map[c.lower()] for c in requested_columns if c.lower() in columns_lower_map]
missing_columns = [c for c in requested_columns if c.lower() not in columns_lower_map]

candidate_training_df = matched_npi_df[selected_actual_columns].head(100).copy()
candidate_training_df.columns = [
    next(req for req in requested_columns if req.lower() == actual.lower())
    for actual in selected_actual_columns
]

if missing_columns:
    print('Missing columns:', missing_columns)

candidate_training_df

Matched rows by NPI: 6

,NPI,degree,educations,experience,certifications,EducationTrainingLocation,EducationTrainingDate,EducationTrainingYears,ResidencyTrainingLocation,ResidencyTrainingDate,ResidencyTrainingYears
2294661,1336109925,MD,"[""Mayo Clinic College of Medicine and Science""...",29.0,[],"[""Mayo Clinic College of Medicine and Science""...","[""Fellowship, Transplant Hepatology, 2005"", ""C...","[[""2005""], [""1993""]]","[""Atlantic Health System"", ""University of Mary...","[""Residency, Internal Medicine, 1998 - 2001"", ...","[[""1998"", ""2001""], [""1997"", ""1998""]]"
3117786,1790076586,PA,[],11.0,[],"[""Other""]",[],"[[""2011""]]",[],[],[]
4357998,1194841254,MD,[],27.0,[],"[""Other""]",[],"[[""1995""]]",[],[],[]
4691593,1457990731,FNP,[],3.0,[],"[""Other""]",[],"[[""2019""]]",[],[],[]
5541773,1518092048,M.D.,"[""Rutgers Robert Wood Johnson Medical School"",...",20.0,[],"[""Rutgers Robert Wood Johnson Medical School""]","[""Class of 2002""]","[[""2002""]]","[""Icahn School of Medicine at Mount Sinai"", ""M...","[""Residency, Urology, 2003 - 2007"", ""Internshi...","[[""2003"", ""2007""], [""2002"", ""2003""]]"
5604134,1063490852,MD. DABPM. FIPP. MBA,"[""University of Miami/Jackson Health System"", ...",34.0,[],"[""University of Miami/Jackson Health System"", ...","[""Fellowship, Pain Medicine, 2001 - 2002"", ""Cl...","[[""2001"", ""2002""], [""1988""]]","[""University of Miami/Jackson Health System"", ...","[""Residency, Anesthesiology, 1996 - 1999"", ""In...","[[""1996"", ""1999""], [""1995"", ""1996""]]"

In [18]:
zocdoc_path = 'zocdoc data.xlsx'
zocdoc_df = pd.read_excel(zocdoc_path, dtype=str)
zocdoc_df = zocdoc_df[zocdoc_df['results'].ne('summary')].copy()

def normalize_npi_column(npi_column):
    return npi_column.astype('string').str.extract(r'(\d{10})', expand=False)

zocdoc_df['NormalizedNPI'] = normalize_npi_column(zocdoc_df['NPI'])
candidate_npis = normalize_npi_column(df['NPI'])

zocdoc_npi_set = set(zocdoc_df['NormalizedNPI'].dropna())
candidate_npi_set = set(candidate_npis.dropna())
matching_zocdoc_npi_set = zocdoc_npi_set.intersection(candidate_npi_set)

zocdoc_matches_df = zocdoc_df[
    zocdoc_df['NormalizedNPI'].isin(matching_zocdoc_npi_set)
].copy()

print(f'Zocdoc rows: {len(zocdoc_df):,}')
print(f'Zocdoc unique NPIs: {len(zocdoc_npi_set):,}')
print(f'Zocdoc unique NPIs in candidates df: {len(matching_zocdoc_npi_set):,}')
print(f'Zocdoc rows with NPIs in candidates df: {len(zocdoc_matches_df):,}')

zocdoc_matches_df.head(20)

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [22]:
def has_non_empty_value(value):
    if isinstance(value, (list, tuple, set, dict)):
        return len(value) > 0
    if value is None or pd.isna(value):
        return False

    value_text = str(value).strip()
    return value_text.lower() not in {'', 'nan', 'null', 'none', '[]'}

zocdoc_matching_npis_df = zocdoc_df[
    zocdoc_df['NormalizedNPI'].isin(matching_zocdoc_npi_set)
].copy()

zocdoc_matches_with_education_df = zocdoc_matching_npis_df[
    zocdoc_matching_npis_df['Education'].map(has_non_empty_value)
].copy()
matching_zocdoc_npis_with_education_set = set(
    zocdoc_matches_with_education_df['NormalizedNPI'].dropna()
)

display_columns = [
    'NormalizedNPI',
    'NPI',
    'Name',
    'Education',
    'Specialty',
    'URL',
]

print(f'Matching Zocdoc rows: {len(zocdoc_matching_npis_df):,}')
print(
    'Matching Zocdoc rows with populated Education: '
    f'{len(zocdoc_matches_with_education_df):,}'
)
print(
    'Unique matching Zocdoc NPIs with populated Education: '
    f'{len(matching_zocdoc_npis_with_education_set):,}'
)

zocdoc_matches_with_education_df[display_columns].head(100)

Matching Zocdoc rows: 45,093
Matching Zocdoc rows with populated Education: 38,128
Unique matching Zocdoc NPIs with populated Education: 37,846

,NormalizedNPI,NPI,Name,Education,Specialty,URL
2,1598801888,#1598801888,Dr. Abbe Wain,Medical School - Icahn School of Medicine at M...,OB-GYN,https://www.zocdoc.com/doctor/abbe-wain-md-195772
3,1942805387,1942805387,Ahmmad Abdul,"State University of New York, Downstate Medica...",Family Nurse Practitioner,https://www.zocdoc.com/doctor/ahmmad-abdul-np-...
4,1811162530,#1811162530,Dr. Avner Aliphas,"Medical School - University of Pennsylvania, D...",Head & Neck Surgeon,https://www.zocdoc.com/doctor/avner-aliphas-md...
5,1063490852,1063490852,Dr. Abel Murillo,"Jackson Memorial Hospital, Residency in Anesth...",Pain Management Specialist,https://www.zocdoc.com/doctor/abel-murillo-md-...
6,1194841254,1194841254,Dr. Abhinav Singh,Medical School - Mahatma Gandhi Memorial Medic...,Internist,https://www.zocdoc.com/doctor/abhinav-singh-md...
...,...,...,...,...,...,...
107,1649519455,#1649519455,Dr. Nader Abdallah,"Medical School - Midwestern University, Chicag...",Family Physician,https://www.zocdoc.com/doctor/nader-abdallah-d...
108,1518059799,#1518059799,Dr. Abel Toledo,Medical School - Federico Villarreal National ...,Primary Care Doctor,https://www.zocdoc.com/doctor/abel-toledo-md-2...
109,1477537322,1477537322,Dr. Abigail Kamishlian,Medical School - University of the Philippines...,Pediatrician,https://www.zocdoc.com/doctor/abigail-kamishli...
110,1194113621,1194113621,Dr. John Johnson,"Northeastern State University, Doctor of Optom...",Optometrist,https://www.zocdoc.com/doctor/john-johnson-od-...
111,1164449666,1164449666,Dr. Andy T. Chung,"Medical School - Loma Linda University, Doctor...","Ear, Nose & Throat Doctor",https://www.zocdoc.com/doctor/andy-t-chung-md-...

In [25]:
additional_npis_to_find = [
    1114059979,
    1174812614,
    1093713166,
    1790990943,
    1184120701,
    1205828449,
    1063437788,
    1104944891,
    1740406933,
    1356336614,
    1730421884,
    1366743056,
    1003870841,
    1285192609,
]

npis_to_find = list(dict.fromkeys([*npis_to_find, *additional_npis_to_find]))

npis_to_find_list = [str(npi).strip() for npi in npis_to_find]
npis_to_find_set = set(npis_to_find_list)
npi_order_df = pd.DataFrame(
    {
        'NormalizedNPI': npis_to_find_list,
        'NPIOrder': range(len(npis_to_find_list)),
    }
)

candidate_columns_lower_map = {column.lower(): column for column in df.columns}
candidate_actual_columns = [
    candidate_columns_lower_map[column.lower()]
    for column in requested_columns
    if column.lower() in candidate_columns_lower_map
]
candidate_column_name_map = {
    actual_column: f'Candidate_{requested_column}'
    for requested_column in requested_columns
    for actual_column in [candidate_columns_lower_map.get(requested_column.lower())]
    if actual_column is not None
}
missing_candidate_columns = [
    column
    for column in requested_columns
    if column.lower() not in candidate_columns_lower_map
]

candidate_lookup_df = df.copy()
candidate_lookup_df['NormalizedNPI'] = normalize_npi_column(candidate_lookup_df['NPI'])
candidate_npis_to_find_df = candidate_lookup_df[
    candidate_lookup_df['NormalizedNPI'].isin(npis_to_find_set)
][['NormalizedNPI', *candidate_actual_columns]].rename(
    columns=candidate_column_name_map
)

zocdoc_lookup_df = zocdoc_df.copy()
zocdoc_lookup_df['NormalizedNPI'] = normalize_npi_column(zocdoc_lookup_df['NPI'])
zocdoc_npis_to_find_df = zocdoc_lookup_df[
    zocdoc_lookup_df['NormalizedNPI'].isin(npis_to_find_set)
][['NormalizedNPI', 'NPI', 'Name', 'Education']].rename(
    columns={
        'NPI': 'Zocdoc_NPI',
        'Name': 'Zocdoc_Name',
        'Education': 'Zocdoc_Education',
    }
)

npi_education_comparison_df = npi_order_df.merge(
    candidate_npis_to_find_df,
    on='NormalizedNPI',
    how='left',
).merge(
    zocdoc_npis_to_find_df,
    on='NormalizedNPI',
    how='left',
).sort_values('NPIOrder').drop(columns=['NPIOrder'])

if missing_candidate_columns:
    print('Missing candidate columns:', missing_candidate_columns)

print(f'Candidate rows for npis_to_find: {len(candidate_npis_to_find_df):,}')
print(f'Zocdoc rows for npis_to_find: {len(zocdoc_npis_to_find_df):,}')
print(f'Comparison rows: {len(npi_education_comparison_df):,}')

with pd.option_context('display.max_colwidth', None):
    display(npi_education_comparison_df)

Candidate rows for npis_to_find: 20
Zocdoc rows for npis_to_find: 21
Comparison rows: 21

,NormalizedNPI,Candidate_NPI,Candidate_degree,Candidate_educations,Candidate_experience,Candidate_certifications,Candidate_EducationTrainingLocation,Candidate_EducationTrainingDate,Candidate_EducationTrainingYears,Candidate_ResidencyTrainingLocation,Candidate_ResidencyTrainingDate,Candidate_ResidencyTrainingYears,Zocdoc_NPI,Zocdoc_Name,Zocdoc_Education
0,1063490852,1063490852,MD. DABPM. FIPP. MBA,"[""University of Miami/Jackson Health System"", ""Fellowship, Pain Medicine, 2001 - 2002"", ""National University of San Marcos"", ""Class of 1988""]",34.0,[],"[""University of Miami/Jackson Health System"", ""National University of San Marcos""]","[""Fellowship, Pain Medicine, 2001 - 2002"", ""Class of 1988""]","[[""2001"", ""2002""], [""1988""]]","[""University of Miami/Jackson Health System"", ""University of Miami/Jackson Health System""]","[""Residency, Anesthesiology, 1996 - 1999"", ""Internship, Transitional Year, 1995 - 1996""]","[[""1996"", ""1999""], [""1995"", ""1996""]]",1063490852,Dr. Abel Murillo,"Jackson Memorial Hospital, Residency in Anesthesiology"
1,1194841254,1194841254,MD,[],27.0,[],"[""Other""]",[],"[[""1995""]]",[],[],[],1194841254,Dr. Abhinav Singh,"Medical School - Mahatma Gandhi Memorial Medical College, Indore, Bachelor of Medicine, Bachelor of SurgerySt. Barnabas Hospital (Residency)"
2,1790076586,1790076586,PA,[],11.0,[],"[""Other""]",[],"[[""2011""]]",[],[],[],1790076586,Abbie Smith,"Butler University, Master's in Physician Assistant StudiesIndiana University (Bachelor's)"
3,1336109925,1336109925,MD,"[""Mayo Clinic College of Medicine and Science"", ""Fellowship, Transplant Hepatology, 2005"", ""Government Medical College Vijayanagar"", ""Class of 1993""]",29.0,[],"[""Mayo Clinic College of Medicine and Science"", ""Government Medical College Vijayanagar""]","[""Fellowship, Transplant Hepatology, 2005"", ""Class of 1993""]","[[""2005""], [""1993""]]","[""Atlantic Health System"", ""University of Maryland Medical Center Midtown Campus""]","[""Residency, Internal Medicine, 1998 - 2001"", ""Internship, Transitional Year, 1997 - 1998""]","[[""1998"", ""2001""], [""1997"", ""1998""]]",1336109925,Dr. Abdullah Mubarak,"Medical School - Vijayanagar Institute of Medical Sciences, Bachelor of Medicine, Bachelor of SurgeryMayo Clinic, Jacksonville, Fellowship in HepatologyMountainside Hospital (Residency)Maryland General Hospital (Internship)"
4,1457990731,1457990731,FNP,[],3.0,[],"[""Other""]",[],"[[""2019""]]",[],[],[],1457990731,Abbeygail Jiongco,"United States University, Master's in Family Nursing"
5,1518092048,1518092048,M.D.,"[""Rutgers Robert Wood Johnson Medical School"", ""Class of 2002""]",20.0,[],"[""Rutgers Robert Wood Johnson Medical School""]","[""Class of 2002""]","[[""2002""]]","[""Icahn School of Medicine at Mount Sinai"", ""Mount Sinai Beth Israel Hospital""]","[""Residency, Urology, 2003 - 2007"", ""Internship, Transitional Year, 2002 - 2003""]","[[""2003"", ""2007""], [""2002"", ""2003""]]",1518092048,Dr. Aaron Grotas,"Medical School - Robert Wood Johnson Medical School, Doctor of MedicineMount Sinai Beth Israel, Internship in SurgeryMount Sinai Beth Israel, Residency in Urology"
6,1518092048,1518092048,M.D.,"[""Rutgers Robert Wood Johnson Medical School"", ""Class of 2002""]",20.0,[],"[""Rutgers Robert Wood Johnson Medical School""]","[""Class of 2002""]","[[""2002""]]","[""Icahn School of Medicine at Mount Sinai"", ""Mount Sinai Beth Israel Hospital""]","[""Residency, Urology, 2003 - 2007"", ""Internship, Transitional Year, 2002 - 2003""]","[[""2003"", ""2007""], [""2002"", ""2003""]]",1518092048,Dr. Aaron Grotas,"Medical School - Rutgers, The State University of New Jersey, Doctor of MedicineBeth Israel Medical Center, Residency in UrologyBeth Israel Medical Center, Internship in Surgery"
7,1114059979,1114059979,MD,[],31.0,[],[],[],[],[],[],[],#1114059979,Nina Molin,"Highland Hospital, Residency, 1994;SuNew York At StoNew York Brook Hlth Sci Center, Medical School, 1991"
8,1174812614,1174812614,M.D.,"[""State University of New York Downstate Medical Center College of Medicine"", ""Class of 2011"", ""The Rockefeller University"", ""Ph.D., 2002 - 2007""]",11.0,[],"[""State University of New York Downstate Medical Center College of Medicine"", ""The Rockefeller University""]","[""Class of 2011"", ""Ph.D., 2002 - 2007""]","[[""2011""], [""2002"", ""2007""]]","[""New York Presbyterian Hospital"", ""Zucker School of Medicine at Hofstra/Northwell""]","[""Residency, Dermatology, 2012 - 2015"", ""Internship, Internal Medicine, 2011 - 2012""]","[[""2012"", ""2015""], [""2011"", ""2012""]]",#1174812614,Dr. Ilana DeLuca,"Medical School - State University of New York, Downstate Medical Center, Doctor of Medicine;Columbia University Medical Center, Residency in Dermatology"
9,1093713166,1093713166,MD,"[""Drexel University College of Medicine/Hahnemann University"", ""Class of 1990""]",32.0,[],"[""Drexel University College of Medicine/Hahnemann University""]","[""Class of 1990""]","[[""1990""]]","[""Drexel University College of Medicine/Hahnemann University""]","[""Residency, Obstetrics and Gynecology, 1990 - 1994""]","[[""1990"", ""1994""]]",#1093713166,Ilene Weizer,"Hahnemann University Hospital, Residency;Hahnemann University School Of Medicine, Medical School, 1990"
10,1790990943,1790990943,M.D.,"[""UMass Chan - Baystate"", ""Fellowship, Nephrology, 2007 - 2009"", ""Royal College of Surgeons Ireland"", ""Class of 2004""]",13.0,[],"[""UMass Chan - Baystate"", ""Royal College of Surgeons Ireland""]","[""Fellowship, Nephrology, 2007 - 2009"", ""Class of 2004""]","[[""2007"", ""2009""], [""2004""]]","[""UMass Chan - Baystate""]","[""Residency, Internal Medicine, 2004 - 2007""]","[[""2004"", ""2007""]]",#1790990943,Eileen Kehoe,"Baystate Medical Center, Residency;Royal College Of Surgeons In Ireland, Medical School, 2004"
11,1184120701,1184120701,DO,"[""College of Osteopathic Medicine of the Pacific"", ""Class of 2018""]",4.0,[],"[""College of Osteopathic Medicine of the Pacific""]","[""Class of 2018""]","[[""2018""]]","[""Kaiser Permanente Southern California""]","[""Residency, Family Medicine, 2018 - 2021""]","[[""2018"", ""2021""]]",#1184120701,Dr. Hannah Barroga,"Medical School - Western University of Health Sciences, College of Osteopathic Medicine of the Pacific, Doctor of Osteopathic Medicine;Kaiser Permanente Riverside Medical Center, Residency in Family Medicine"
12,1205828449,1205828449,MD,[],39.0,[],"[""Other""]",[],"[[""1983""]]",[],[],[],#1205828449,Mohammad Ilyas,"Northwestern University Medical Sch, Residency;Quaid-E-Azam Medical College, Medical School, 1983"
13,1063437788,1063437788,MD,[],44.0,[],"[""Stanford University School Of Medicine""]",[],"[[""1978""]]",[],[],[],#1063437788,Harriet Bering,"Stanford University School Of Medicine, Medical School, 1978;Yale New Haven Hospital, Residency, 1982"
14,1104944891,1104944891,MD,"[""McGaw Medical Center of Northwestern University"", ""Class of 2003""]",19.0,[],"[""McGaw Medical Center of Northwestern University""]","[""Class of 2003""]","[[""2003""]]","[""University of Michigan Health System"", ""University of Michigan Health System""]","[""Residency, Dermatology, 2004 - 2007"", ""Internship, Internal Medicine, 2003 - 2004""]","[[""2004"", ""2007""], [""2003"", ""2004""]]",#1104944891,Dr. Nicole Neuschler,"Medical School - Northwestern University, Doctor of Medicine;University of Michigan, Residency in Dermatology"
15,1740406933,1740406933,M.D.,"[""New York Presbyterian Hospital"", ""Fellowship, Child and Adolescent Psychiatry, 1992 - 1994"", ""Icahn School of Medicine at Mount Sinai"", ""Class of 1988""]",0.0,[],"[""New York Presbyterian Hospital"", ""Icahn School of Medicine at Mount Sinai""]","[""Fellowship, Child and Adolescent Psychiatry, 1992 - 1994"", ""Class of 1988""]","[[""1992"", ""1994""], [""1988""]]","[""New York Presbyterian Hospital""]","[""Residency, Psychiatry, 1988 - 1992""]","[[""1988"", ""1992""]]",1740406933,Ilene Rabinowitz,"Mt Sinai School Of Medical Of The City University Of New YorkMedical School, 1988Ny & Presby Hp-Columbia CampusResidency"
16,1356336614,1356336614,DPM,[],22.0,[],"[""New York College Of Podiatric Medicine""]",[],"[[""2000""]]",[],[],[],#1356336614,Dr. Ilana Itenberg,"New York College of Podiatric Medicine, Doctor of Podiatric Medicine;Saint Barnabas Medical Center, Residency in Surgery"
17,1730421884,1730421884,D.P.M.,[],9.0,[],"[""Other""]",[],"[[""2013""]]",[],[],[],1730421884,Dr. Hannah Park,"Rosalind Franklin University of Medicine and Science, Doctor of Podiatric MedicineJesse Brown Veterans Affairs Medical Center, Residency in Podiatric MedicineJesse Brown Veterans Affairs Medical Center, Residency in General SurgeryAdvocate Christ Medical Center, Fellowship in Pediatric Orthopaedics"
18,1366743056,1366743056,PA-C,[],12.0,[],"[""Other""]",[],"[[""2010""]]",[],[],[],1366743056,Rita Patel,"Philadelphia University + Thomas Jefferson University, Master's in Physician Assistant Medicine"
19,1003870841,1003870841,D.P.M.,[],43.0,[],"[""Other""]",[],"[[""1979""]]",[],[],[],1003870841,Dr. Arnold Ravick,"Temple University, Doctor of Podiatric MedicineTemple University (Residency)"
20,1285192609,1285192609,"RDN, CDCES, LRD",[],0.0,[],[null],[],[],[],[],[],1285192609,Samantha Jerome,"University of Arizona, Bachelor's in DieteticsMaricopa County Department of Public Health, Internship in Dietetics"